# Generated by Django 4.2.3 on 2023-08-22 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
    ]
