# Generated by Django 4.2.3 on 2023-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_transection_tr_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transection',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
