# Generated by Django 4.2.3 on 2023-08-23 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_alter_transection_balance_alter_transection_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 24)),
        ),
    ]
