# Generated by Django 4.2.3 on 2023-08-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_user_table_flag_alter_transection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_table',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
