# Generated by Django 4.2.3 on 2023-08-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_user_table_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'AdminDb',
            },
        ),
    ]
