# Generated by Django 4.2.3 on 2023-08-31 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_admindb'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_table',
            name='card',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_table',
            name='cvv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transection',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 1)),
        ),
    ]
